### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by melihbirim**
Typo fix commands in README
4-nodes-raft sample added

### CODE REVIEW

**Comment by libby** [comment]
Thanks @melihbirim! can you include just the README typo fix in this PR? Then I can merge. 

For the `7nodes/4-nodes-raft` could you open a new PR and explain why this is needed verse being generate via `qctl`?

**Comment by melihbirim** [comment]
Hello @libby , I removed the 4-nodes-raft folder .

Basically, 4-nodes-raft is for simple network configuration without tessera and privacy. I could not find a way or direction in documentation not to include tessera or constellation on Quorum network setup. 

If there is a way, can you please share it how I can achieve this?

**Comment by libby** [comment]
Thanks @melihbirim, will merge this, and then can you open an issue for including support for running quorum without the transaction manager? Then we can automate this and add it to `qctl` as well. cc/ @apratt3377

**Review by apratt3377 — APPROVED** [review]
@melihbirim - changes look good, but can you please bring it up to date with the base branch

**Pull request merged**
