### PR TITLE
Puts flag in features object in tessera config

### PR DESCRIPTION
**Pull request by bmcd**

### CODE REVIEW

**Comment by bmcd** [comment]
The enablePrivacyEnhancements flag is supposed to be inside the 'features' object in the tessera config, not a top level value.

**Comment by bmcd** [comment]
Before the change, when running Tessera 20.10.0 the logs during startup would warn:
```
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enablePrivacyEnhancements
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enablePrivacyEnhancements
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
WARN  c.q.t.c.c.NoUnmatchedElementsValidator - Ignoring unknown/unmatched json element: enabled
```
The enabled flag was removed in tessera 0.10.x I believe, so that warning is to be expected. After the fix, only the enabled warnings show and the enablePrivacyEnhancements warning no longer shows.

If you run against tessera 0.11.0 or lower, the new flag _will_ be ignored and show up in logs as above.

**Comment by bmcd** [comment]
A note about Quorum behavior with the enhanced privacy flags:

When Quorum sees that privacyEnhancementsBlock is included in the genesis file, it checks to make sure that the transaction manager it is connected to supports this feature. So if you were running Tessera 0.11.0 or lower, it would throw an error on quorum startup saying that privacy enhancements are not supported. This also happens if you have no transaction manager at all (this isn't supported in Qubernetes itself, but can be an issue if you use the Quberetes docker container for generating resources for a network, like Wizard does for docker-compose).

So I added Tessera_Version in the genesis config block in qubernetes.yaml, which is checked before including the flag in the genesis file. The flag in the Tessera config is safely ignored in older versions, so no need to add logic to exclude writing that flag.

**Comment by libby** [comment]
Added tests for new versions  `./test.sh qversions` and updated `qctl`  to support adding the tm version to the genesis section of the config.

**Review by libby — APPROVED** [review]
LGTM

**Pull request merged**
